export default {
  emailaddress: () => cy.get('#signInName'),
  password: () => cy.get('#password'),
  loginwithpassword: () => cy.contains('button', 'Log in with password'),
  myapplications: () => cy.contains('div', 'My applications'),
  familyimmigration: () => cy.contains('h1', 'Family immigration'),
  previouspage: () => cy.contains('span', 'Previous page'),
  nextpage: () => cy.contains('span', 'Next page'),
  logout: () => cy.contains('span', 'Log out'),
  self_first_and_middlename: () => cy.contains('div', 'What is the name of the person who wants to live in Norway?').parent().contains('label', 'First (and middle) name').parent().find('input'),
  self_lastname: () => cy.contains('div', 'What is the name of the person who wants to live in Norway?').parent().contains('label', 'Last name').parent().find('input'),
  self_country: () => cy.contains('div', 'Which country are you a citizen of?').parent().contains('label', 'Country').parent().find('input'),
  family_member_country: () => cy.contains('div', 'Which country is the family member in Norway a citizen of?').parent().contains('label', 'Country').parent().find('input'),
  checkcitizenship: () => cy.contains('div', 'Do you have more than one citizenship?').parent().find('label').contains('No'),
  family: () => cy.contains('th', 'Family').parent().find('a'),
  familymember: () => cy.contains('label', 'Family member').parent().find('input'),

  bekreft: () => cy.get('[type="checkbox"]'),
  family_member_first_and_middlename: () => cy.contains('div', 'What is the name of the family member in Norway?').parent().contains('label', 'First (and middle) name').parent().find('input'),
  family_member_lastname: () => cy.contains('div', 'What is the name of the family member in Norway?').parent().contains('label', 'Last name').parent().find('input'),
  leve_sammen: () => cy.contains('div', 'Are you going to live together in Norway?').parent().find('label').contains('Yes'),
  residence_permit_in_another_country: () => cy.contains('div', 'Do you have a residence permit in another EU/EEA country than Norway?').parent().contains('span', 'No'),
  family_residence_permit_type: () => cy.contains('div', 'What kind of residence permit does the family member who lives in Norway have?').parent().contains('span', 'Work'),
  family_member_identity_number: () => cy.contains('div', 'National identity number or D number (OPTIONAL)').parent().find('input'),
  current_country: () => cy.contains('div', 'Which country do you live in now?').parent().find('input'),
  family_member_dob: () => cy.contains('div', 'Birth date in the format DD.MM.YYYY').parent().find('input'),

  //Samples
  klientnavnlabel: () => cy.contains('label', 'Klientnavn'),
  brukerinfo: () => cy.get('[data="ci-bruker"]'),
  tabell: {
    operasjonssentral: () => cy.contains('a', 'Operasjonssentral'),
    posisjon: () => cy.contains('a', 'Posisjon'),
    klientnavn: () => cy.contains('a', 'Klientnavn'),
  },
  klientnavn: () => cy.contains('label', 'Klientnavn').parent().find('input'),
  posisjon: () => cy.contains('label', 'Posisjon').parent().find('input'),
  modalklientnavn: () => cy.get('.modal-content').contains('Klientnavn').parent().find('input'),
  organisasjonlabel: () => cy.contains('label', 'Organisasjon'),
  organisasjon: () => cy.contains('label', 'Organisasjon').parent().find('select'),
  registerArbeidstasjon: () => cy.contains('button', 'Registrer arbeidsstasjon'),
  redigereArbeidstasjon: (klientnavn: string) => cy.contains('td', klientnavn).siblings().contains('button', 'Rediger'),
  slettArbeidstasjon: (klientnavn: string) => cy.contains('td', klientnavn).siblings().contains('button', 'Slett'),
  bekreftSletting: () => cy.contains('button', 'Ja, slett arbeidsstasjon'),
  nullstill: () => cy.contains('button', 'Nullstill'),
  søk: () => cy.contains('button', 'Søk'),
  lagreendringer: () => cy.contains('button', 'Lagre endringer'),
  opprettArbeidstasjon: () => cy.contains('button', 'Opprett arbeidsstasjon'),
  avbrytOpprettArbeidstasjon: () => cy.contains('button', 'Avbryt'),
  alertmelding: () => cy.get('melding'),
  cardtext: () => cy.get('.card-text'),
  arbeidsstasjonertabellråder: () => cy.get('arbeidsstasjoner-tabell tr'),
};
