export default {
  emailaddress: () => cy.get('#signInName'),
  password: () => cy.get('#password'),
  loginwithpassword: () => cy.contains('button', 'Log in with password'),
  myapplications: () => cy.contains('div', 'My applications'),
  familyimmigration: () => cy.contains('h1', 'Family immigration'),
  previouspage: () => cy.contains('span', 'Previous page'),
  nextpage: () => cy.contains('span', 'Next page'),
  submit: () => cy.contains('button', 'Submit'),
  logout: () => cy.contains('span', 'Log out'),
  self_first_and_middlename: () => cy.contains('div', 'What is the name of the person who wants to live in Norway?').parent().contains('label', 'First (and middle) name').parent().find('input'),
  self_lastname: () => cy.contains('div', 'What is the name of the person who wants to live in Norway?').parent().contains('label', 'Last name').parent().find('input'),
  self_country: () => cy.contains('div', 'Which country are you a citizen of?').parent().contains('label', 'Country').parent().find('input'),
  family_member_country: () => cy.contains('div', 'Which country is the family member in Norway a citizen of?').parent().contains('label', 'Country').parent().find('input'),
  family_member_current_status: () => cy.contains('div', 'What is your family member in Norway doing?').parent().contains('label', 'Select what your family member is doing').parent().find('input'),
  checkcitizenship: () => cy.contains('div', 'Do you have more than one citizenship?').parent().find('label').contains('No'),
  family: () => cy.contains('th', 'Family').parent().find('a'),
  familymember: () => cy.contains('label', 'Family member').parent().find('input'),
  place_of_birth: () => cy.contains('label', 'Place of birth').parent().find('input'),
  bekreft: () => cy.get('[type="checkbox"]'),
  family_member_first_and_middlename: () => cy.contains('div', 'What is the name of the family member in Norway?').parent().contains('label', 'First (and middle) name').parent().find('input'),
  family_member_lastname: () => cy.contains('div', 'What is the name of the family member in Norway?').parent().contains('label', 'Last name').parent().find('input'),
  leve_sammen: () => cy.contains('div', 'Are you going to live together in Norway?').parent().find('label').contains('Yes'),
  married_before: () => cy.contains('div', 'Has your partner been married to a person from the same country as you in the past?').parent().contains('span', 'No'),
  children: () => cy.contains('div', 'Do you have children of your own?').parent().contains('span', 'No'),
  gender: () => cy.contains('div', 'What is your gender?').parent().contains('span', 'Female'),
  family_member_salary: () => cy.contains('div', 'Did the family member in Norway earn more than 300 000 Norwegian kroner before tax last year?').parent().contains('span', 'Yes'),
  family_member_another_source_salary: () => cy.contains('div', 'Did your family member have another source of income last year?').parent().contains('span', 'No'),
  residence_permit_in_another_country: () => cy.contains('div', 'Do you have a residence permit in another EU/EEA country than Norway?').parent().contains('span', 'No'),
  family_residence_permit_type: () => cy.contains('div', 'What kind of residence permit does the family member who lives in Norway have?').parent().contains('span', 'Work'),
  who_delivers_documents: () => cy.contains('div', 'Who will be handing in your application documents?').parent().contains('span', 'I will hand in my application documents myself'),
  family_member_identity_number: () => cy.contains('div', 'National identity number or D number (OPTIONAL)').parent().find('input'),
  current_country: () => cy.contains('div', 'Which country do you live in now?').parent().find('input'),
  country_of_birth: () => cy.contains('div', 'Which country were you born in?').parent().find('input'),
  family_member_dob: () => cy.contains('div', 'Birth date in the format DD.MM.YYYY').parent().find('input'),
  self_dob: () => cy.contains('div', 'Birth date in the format DD.MM.YYYY').parent().find('input'),
  saved: () => cy.contains('div', 'We have saved your answers.'),
};
