### Kontrollrom Ping request
GET {{host}}/ping
Authorization: oauth2 password
Accept: application/json
kallId:1
konsument: Postman
miljo: test

?? status == 200
?? body includes versjon

>>! ../output/pingResponse.json

### Hent Arbeidstasjoner i Kontrollrom
GET {{host}}/api/kontrollrom/{{districtID}}/arbeidsstasjon?navneFiltrering=
Authorization: oauth2 password
Accept: application/json
kallId:1
konsument: Postman
miljo: test

?? status == 200
?? body includes id
?? body includes distriktId
?? body includes operasjonssentral
?? body includes posisjon
?? body includes klientnavn

>>! ../output/hentArbeidstasjonerResponse.json

### Register Ny Arbeidsstasjon
# @disabled
POST {{host}}/api/kontrollrom/201/arbeidsstasjon
Authorization: oauth2 password
Content-Type: application/json
Accept: application/json
kallId:1
konsument: Postman
miljo: test

<@ ../input/NyArbeidsstasjon.json

?? status == 200